### ISSUE TITLE
Generate nice ID base on  MongoDB ObjectID

### ISSUE THREAD

**Issue by dawjan** [ivanakimov/hashids.php#39]
I try to find way to replace MongoDB objectID with Nice id that i can use even in URL

`$toHash = '55a3f9bdd874595813000029';`
`$hashids = new \Hashids\Hashids( 'Coll global salt' );`
`//$toHash = preg_replace('/[a-zA-Z]+/', '', $toHash); //collision or not collision this is question :p`
`$toHash = str_replace(range('a', 'z'),range(0,9),$toHash); // or better one - avoid dual numbers`
`$ID = explode('#',chunk_split($toHash,9,'#',-1));`
`echo $hashids->encode( $ID  ) . '<br />';`

Results:
`55c21840e12f92701400002b => bKlpzGs2R7qvC6`
`55a3f9bdd874595813000029 => pQR0p6atY1tRrYvqU87RZZi4`

Also will be nice if we had function:
`$hashids = new \Hashids\Hashids( 'Globaluhashuu' );`
`$hashids->MongoID_encode('55a3f9bdd874595813000029')  => bKlpzGs2R7qvC6`
`$hashids->MongoID_decode('bKlpzGs2R7qvC6')  => 55a3f9bdd874595813000029`

**Comment by ivanakimov** [comment]
I'm going to guess that you're trying to figure out a better way to compress Mongo's IDs because the current output is kinda lengthy.

There are two problems with your code that I see:

1. When you do `preg_replace` with `''`, you cannot safely encode/decode "5ab3" and "a53b". And when you do `str_replace` with range, you cannot safely decode because you don't know which integer was a letter (`5a` => `50` or `50` => `50`?).
2. Additionally, your `chunk_split` will have an issue when you split a string like this: "200003", because encode will think you're encoding **200** and **3**, when you should be encoding **200** and **003**.

So, to answer your question -- yes, looks like you'll definitely have collisions with these methods.

**Comment by dawjan** [comment]
55a3f9bdd874595813000029 => 920000318595478ddb9f3a55 =>  920000318595478331953055

[0] => 920000318 
[1] => 595478331 
[2] => 953055
[3] => time(1)

Right now i;m not care about decrypt ID back, need be only be uniq, so i think to add mt_rand ord time(1) as additional param. Also MongoDB ids are normal ended with 0000001 so i just strrev base ID. So som kind of hard-fix.

Thank you for your patience

**Comment by ivanakimov** [comment]
If you need them to be unique, I don't recommend doing what you're proposing, because you **will** generate duplicate ids (irregardless of what additional parameters you'll add). I'm not aware of any safer method other than the one provided by `encode_hex` and `decode_hex`.

**Comment by dawjan** [comment]
`$id = new \MongoId($toHash);`

`echo $h->encode([$id->getTimestamp(),$id->getInc(),$id->getPID(),preg_replace('/[a-zA-Z]+/', '', substr($toHash,8,6))]);`

![ObjID](http://cacodaemon.de/images/65.png)

55c1f1f4e12f92d814000031
Timestamp: 1438773748
Hostname2: 1292 //MD5 3 bytes :: -A_Z
ProcesID: 5336
Increment: 49
0DWpDj6ulYUL3ZuR5

Tested on 2milion rows no duplicate, so this method is i think more clean

**Comment by ivanakimov** [comment]
Hi @dawjan, yes that's one of the methods listed under http://hashids.org/#alternatives (#2). That's good that you didn't get duplicates for the first 2m rows.
